platform: linux
image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/cryogenics/essentials
    tag: 0.1.102
inputs:
  - name: backup-and-restore-sdk-release
  - name: terraform-state
  - name: gcp-db-certs-zip
outputs:
  - name: gcp-db-certs-zip
params:
  GCP_SERVICE_ACCOUNT_KEY:
  ZIP_PASSWORD: ((bbr/db-cert-zip-password.pass))
run:
  path: backup-and-restore-sdk-release/ci/tasks/create-gcp-db-certs/task.sh
