// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/database-backup-restore/config"
	"github.com/cloudfoundry-incubator/database-backup-restore/database"
	"github.com/cloudfoundry-incubator/database-backup-restore/version"
)

type FakeServerVersionDetector struct {
	GetVersionStub        func(config.ConnectionConfig) (version.SemanticVersion, error)
	getVersionMutex       sync.RWMutex
	getVersionArgsForCall []struct {
		arg1 config.ConnectionConfig
	}
	getVersionReturns struct {
		result1 version.SemanticVersion
		result2 error
	}
	getVersionReturnsOnCall map[int]struct {
		result1 version.SemanticVersion
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeServerVersionDetector) GetVersion(arg1 config.ConnectionConfig) (version.SemanticVersion, error) {
	fake.getVersionMutex.Lock()
	ret, specificReturn := fake.getVersionReturnsOnCall[len(fake.getVersionArgsForCall)]
	fake.getVersionArgsForCall = append(fake.getVersionArgsForCall, struct {
		arg1 config.ConnectionConfig
	}{arg1})
	fake.recordInvocation("GetVersion", []interface{}{arg1})
	fake.getVersionMutex.Unlock()
	if fake.GetVersionStub != nil {
		return fake.GetVersionStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getVersionReturns.result1, fake.getVersionReturns.result2
}

func (fake *FakeServerVersionDetector) GetVersionCallCount() int {
	fake.getVersionMutex.RLock()
	defer fake.getVersionMutex.RUnlock()
	return len(fake.getVersionArgsForCall)
}

func (fake *FakeServerVersionDetector) GetVersionArgsForCall(i int) config.ConnectionConfig {
	fake.getVersionMutex.RLock()
	defer fake.getVersionMutex.RUnlock()
	return fake.getVersionArgsForCall[i].arg1
}

func (fake *FakeServerVersionDetector) GetVersionReturns(result1 version.SemanticVersion, result2 error) {
	fake.GetVersionStub = nil
	fake.getVersionReturns = struct {
		result1 version.SemanticVersion
		result2 error
	}{result1, result2}
}

func (fake *FakeServerVersionDetector) GetVersionReturnsOnCall(i int, result1 version.SemanticVersion, result2 error) {
	fake.GetVersionStub = nil
	if fake.getVersionReturnsOnCall == nil {
		fake.getVersionReturnsOnCall = make(map[int]struct {
			result1 version.SemanticVersion
			result2 error
		})
	}
	fake.getVersionReturnsOnCall[i] = struct {
		result1 version.SemanticVersion
		result2 error
	}{result1, result2}
}

func (fake *FakeServerVersionDetector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getVersionMutex.RLock()
	defer fake.getVersionMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeServerVersionDetector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ database.ServerVersionDetector = new(FakeServerVersionDetector)
