#!/usr/bin/env bash

set -e

export PG_DUMP_9_4_PATH="/mysqldump"
export PG_RESTORE_9_4_PATH="/mysql"

export PG_DUMP_9_6_PATH="/mysqldump"
export PG_RESTORE_9_6_PATH="/mysql"

export PG_DUMP_10_PATH="/mysqldump"
export PG_RESTORE_10_PATH="/mysql"

export PG_DUMP_11_PATH="/mysqldump"
export PG_RESTORE_11_PATH="/mysql"

export PG_DUMP_13_PATH="/mysqldump"
export PG_RESTORE_13_PATH="/mysql"

export PG_CLIENT_PATH="/var/vcap/packages/database-backup-restorer-postgres-13/bin/psql"

export MARIADB_DUMP_PATH="/mysqldump"
export MARIADB_CLIENT_PATH="/mysql"

export MYSQL_DUMP_5_6_PATH="/mysqldump"
export MYSQL_CLIENT_5_6_PATH="/mysql"

export MYSQL_DUMP_5_7_PATH="/mysqldump"
export MYSQL_CLIENT_5_7_PATH="/mysql"

export MYSQL_DUMP_8_0_PATH="/mysqldump"
export MYSQL_CLIENT_8_0_PATH="/mysql"

/var/vcap/packages/database-backup-restorer/bin/database-backup-restore --backup $*
