// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"database-backup-restore/database"
	"sync"
)

type FakeTableChecker struct {
	FindMissingTablesStub        func([]string) ([]string, error)
	findMissingTablesMutex       sync.RWMutex
	findMissingTablesArgsForCall []struct {
		arg1 []string
	}
	findMissingTablesReturns struct {
		result1 []string
		result2 error
	}
	findMissingTablesReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTableChecker) FindMissingTables(arg1 []string) ([]string, error) {
	var arg1Copy []string
	if arg1 != nil {
		arg1Copy = make([]string, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.findMissingTablesMutex.Lock()
	ret, specificReturn := fake.findMissingTablesReturnsOnCall[len(fake.findMissingTablesArgsForCall)]
	fake.findMissingTablesArgsForCall = append(fake.findMissingTablesArgsForCall, struct {
		arg1 []string
	}{arg1Copy})
	fake.recordInvocation("FindMissingTables", []interface{}{arg1Copy})
	fake.findMissingTablesMutex.Unlock()
	if fake.FindMissingTablesStub != nil {
		return fake.FindMissingTablesStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findMissingTablesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTableChecker) FindMissingTablesCallCount() int {
	fake.findMissingTablesMutex.RLock()
	defer fake.findMissingTablesMutex.RUnlock()
	return len(fake.findMissingTablesArgsForCall)
}

func (fake *FakeTableChecker) FindMissingTablesCalls(stub func([]string) ([]string, error)) {
	fake.findMissingTablesMutex.Lock()
	defer fake.findMissingTablesMutex.Unlock()
	fake.FindMissingTablesStub = stub
}

func (fake *FakeTableChecker) FindMissingTablesArgsForCall(i int) []string {
	fake.findMissingTablesMutex.RLock()
	defer fake.findMissingTablesMutex.RUnlock()
	argsForCall := fake.findMissingTablesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeTableChecker) FindMissingTablesReturns(result1 []string, result2 error) {
	fake.findMissingTablesMutex.Lock()
	defer fake.findMissingTablesMutex.Unlock()
	fake.FindMissingTablesStub = nil
	fake.findMissingTablesReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeTableChecker) FindMissingTablesReturnsOnCall(i int, result1 []string, result2 error) {
	fake.findMissingTablesMutex.Lock()
	defer fake.findMissingTablesMutex.Unlock()
	fake.FindMissingTablesStub = nil
	if fake.findMissingTablesReturnsOnCall == nil {
		fake.findMissingTablesReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.findMissingTablesReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeTableChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.findMissingTablesMutex.RLock()
	defer fake.findMissingTablesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTableChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ database.TableChecker = new(FakeTableChecker)
