// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	gcs "github.com/cloudfoundry-incubator/gcs-blobstore-backup-restore"
)

type FakeBackuper struct {
	CreateLiveBucketSnapshotStub        func() error
	createLiveBucketSnapshotMutex       sync.RWMutex
	createLiveBucketSnapshotArgsForCall []struct{}
	createLiveBucketSnapshotReturns     struct {
		result1 error
	}
	createLiveBucketSnapshotReturnsOnCall map[int]struct {
		result1 error
	}
	CopyBlobsWithinBackupBucketStub        func(backupBucketAddresses map[string]gcs.BackupBucketAddress) error
	copyBlobsWithinBackupBucketMutex       sync.RWMutex
	copyBlobsWithinBackupBucketArgsForCall []struct {
		backupBucketAddresses map[string]gcs.BackupBucketAddress
	}
	copyBlobsWithinBackupBucketReturns struct {
		result1 error
	}
	copyBlobsWithinBackupBucketReturnsOnCall map[int]struct {
		result1 error
	}
	TransferBlobsToBackupBucketStub        func() (map[string]gcs.BackupBucketAddress, error)
	transferBlobsToBackupBucketMutex       sync.RWMutex
	transferBlobsToBackupBucketArgsForCall []struct{}
	transferBlobsToBackupBucketReturns     struct {
		result1 map[string]gcs.BackupBucketAddress
		result2 error
	}
	transferBlobsToBackupBucketReturnsOnCall map[int]struct {
		result1 map[string]gcs.BackupBucketAddress
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBackuper) CreateLiveBucketSnapshot() error {
	fake.createLiveBucketSnapshotMutex.Lock()
	ret, specificReturn := fake.createLiveBucketSnapshotReturnsOnCall[len(fake.createLiveBucketSnapshotArgsForCall)]
	fake.createLiveBucketSnapshotArgsForCall = append(fake.createLiveBucketSnapshotArgsForCall, struct{}{})
	fake.recordInvocation("CreateLiveBucketSnapshot", []interface{}{})
	fake.createLiveBucketSnapshotMutex.Unlock()
	if fake.CreateLiveBucketSnapshotStub != nil {
		return fake.CreateLiveBucketSnapshotStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.createLiveBucketSnapshotReturns.result1
}

func (fake *FakeBackuper) CreateLiveBucketSnapshotCallCount() int {
	fake.createLiveBucketSnapshotMutex.RLock()
	defer fake.createLiveBucketSnapshotMutex.RUnlock()
	return len(fake.createLiveBucketSnapshotArgsForCall)
}

func (fake *FakeBackuper) CreateLiveBucketSnapshotReturns(result1 error) {
	fake.CreateLiveBucketSnapshotStub = nil
	fake.createLiveBucketSnapshotReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBackuper) CreateLiveBucketSnapshotReturnsOnCall(i int, result1 error) {
	fake.CreateLiveBucketSnapshotStub = nil
	if fake.createLiveBucketSnapshotReturnsOnCall == nil {
		fake.createLiveBucketSnapshotReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createLiveBucketSnapshotReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBackuper) CopyBlobsWithinBackupBucket(backupBucketAddresses map[string]gcs.BackupBucketAddress) error {
	fake.copyBlobsWithinBackupBucketMutex.Lock()
	ret, specificReturn := fake.copyBlobsWithinBackupBucketReturnsOnCall[len(fake.copyBlobsWithinBackupBucketArgsForCall)]
	fake.copyBlobsWithinBackupBucketArgsForCall = append(fake.copyBlobsWithinBackupBucketArgsForCall, struct {
		backupBucketAddresses map[string]gcs.BackupBucketAddress
	}{backupBucketAddresses})
	fake.recordInvocation("CopyBlobsWithinBackupBucket", []interface{}{backupBucketAddresses})
	fake.copyBlobsWithinBackupBucketMutex.Unlock()
	if fake.CopyBlobsWithinBackupBucketStub != nil {
		return fake.CopyBlobsWithinBackupBucketStub(backupBucketAddresses)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.copyBlobsWithinBackupBucketReturns.result1
}

func (fake *FakeBackuper) CopyBlobsWithinBackupBucketCallCount() int {
	fake.copyBlobsWithinBackupBucketMutex.RLock()
	defer fake.copyBlobsWithinBackupBucketMutex.RUnlock()
	return len(fake.copyBlobsWithinBackupBucketArgsForCall)
}

func (fake *FakeBackuper) CopyBlobsWithinBackupBucketArgsForCall(i int) map[string]gcs.BackupBucketAddress {
	fake.copyBlobsWithinBackupBucketMutex.RLock()
	defer fake.copyBlobsWithinBackupBucketMutex.RUnlock()
	return fake.copyBlobsWithinBackupBucketArgsForCall[i].backupBucketAddresses
}

func (fake *FakeBackuper) CopyBlobsWithinBackupBucketReturns(result1 error) {
	fake.CopyBlobsWithinBackupBucketStub = nil
	fake.copyBlobsWithinBackupBucketReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBackuper) CopyBlobsWithinBackupBucketReturnsOnCall(i int, result1 error) {
	fake.CopyBlobsWithinBackupBucketStub = nil
	if fake.copyBlobsWithinBackupBucketReturnsOnCall == nil {
		fake.copyBlobsWithinBackupBucketReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.copyBlobsWithinBackupBucketReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBackuper) TransferBlobsToBackupBucket() (map[string]gcs.BackupBucketAddress, error) {
	fake.transferBlobsToBackupBucketMutex.Lock()
	ret, specificReturn := fake.transferBlobsToBackupBucketReturnsOnCall[len(fake.transferBlobsToBackupBucketArgsForCall)]
	fake.transferBlobsToBackupBucketArgsForCall = append(fake.transferBlobsToBackupBucketArgsForCall, struct{}{})
	fake.recordInvocation("TransferBlobsToBackupBucket", []interface{}{})
	fake.transferBlobsToBackupBucketMutex.Unlock()
	if fake.TransferBlobsToBackupBucketStub != nil {
		return fake.TransferBlobsToBackupBucketStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.transferBlobsToBackupBucketReturns.result1, fake.transferBlobsToBackupBucketReturns.result2
}

func (fake *FakeBackuper) TransferBlobsToBackupBucketCallCount() int {
	fake.transferBlobsToBackupBucketMutex.RLock()
	defer fake.transferBlobsToBackupBucketMutex.RUnlock()
	return len(fake.transferBlobsToBackupBucketArgsForCall)
}

func (fake *FakeBackuper) TransferBlobsToBackupBucketReturns(result1 map[string]gcs.BackupBucketAddress, result2 error) {
	fake.TransferBlobsToBackupBucketStub = nil
	fake.transferBlobsToBackupBucketReturns = struct {
		result1 map[string]gcs.BackupBucketAddress
		result2 error
	}{result1, result2}
}

func (fake *FakeBackuper) TransferBlobsToBackupBucketReturnsOnCall(i int, result1 map[string]gcs.BackupBucketAddress, result2 error) {
	fake.TransferBlobsToBackupBucketStub = nil
	if fake.transferBlobsToBackupBucketReturnsOnCall == nil {
		fake.transferBlobsToBackupBucketReturnsOnCall = make(map[int]struct {
			result1 map[string]gcs.BackupBucketAddress
			result2 error
		})
	}
	fake.transferBlobsToBackupBucketReturnsOnCall[i] = struct {
		result1 map[string]gcs.BackupBucketAddress
		result2 error
	}{result1, result2}
}

func (fake *FakeBackuper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createLiveBucketSnapshotMutex.RLock()
	defer fake.createLiveBucketSnapshotMutex.RUnlock()
	fake.copyBlobsWithinBackupBucketMutex.RLock()
	defer fake.copyBlobsWithinBackupBucketMutex.RUnlock()
	fake.transferBlobsToBackupBucketMutex.RLock()
	defer fake.transferBlobsToBackupBucketMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBackuper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gcs.Backuper = new(FakeBackuper)
