platform: linux
image_resource:
  type: registry-image
  source:
    repository: cryogenics/essentials
    tag: 0.1.58
inputs:
  - name: backup-and-restore-sdk-release
  - name: mysql-5.6-release
outputs:
  - name: release-with-updated-mysql-release
run:
  path: backup-and-restore-sdk-release/ci/tasks/bump-mysql-5.6/task.sh
