#!/usr/bin/env bash

set -e

export PG_DUMP_PATH="/var/vcap/packages/database-backup-restorer-postgres/bin/pg_dump"
export MYSQL_DUMP_PATH="/var/vcap/packages/database-backup-restorer-mysql/bin/mysqldump"
export MYSQL_CLIENT_PATH="/var/vcap/packages/database-backup-restorer-mysql/bin/mysql"

/var/vcap/packages/database-backup-restorer/bin/database-backup-restore --backup $*
