#!/bin/bash

source $(dirname $0)/check.bash

input=$(timeout 0.5s cat)

product=$(echo $input | jq --raw-output -c '.source.product')

xml=$(curl 'https://dev.mysql.com/downloads/rss.php' --silent)

latest_version=$(echo $xml | get_latest_release $product)

echo $(build_output $latest_version)