#!/bin/bash

source in.bash

destination_dir="${1:?destination_dir not specified}"
input=$(timeout 0.5s cat)

version=$(echo $input | jq --raw-output -c '.version.ref')

download_url=$(get_download_url $version)

download_file $download_url $destination_dir

echo $(build_output $version)