platform: linux
image_resource:
  type: registry-image
  source:
    repository: cryogenics/essentials
    tag: 0.1.59
inputs:
  - name: version
  - name: backup-and-restore-sdk-release
outputs:
  - name: backup-and-restore-sdk-release-build
params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  RELEASE_NAME:
run:
  path: backup-and-restore-sdk-release/ci/tasks/create-dev-release/task.sh
