// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/s3-blobstore-backup-restore/unversioned"
)

type FakeBucketPair struct {
	CheckValidityStub        func() error
	checkValidityMutex       sync.RWMutex
	checkValidityArgsForCall []struct{}
	checkValidityReturns     struct {
		result1 error
	}
	checkValidityReturnsOnCall map[int]struct {
		result1 error
	}
	BackupStub        func(backupLocation string) (unversioned.BackupBucketAddress, error)
	backupMutex       sync.RWMutex
	backupArgsForCall []struct {
		backupLocation string
	}
	backupReturns struct {
		result1 unversioned.BackupBucketAddress
		result2 error
	}
	backupReturnsOnCall map[int]struct {
		result1 unversioned.BackupBucketAddress
		result2 error
	}
	RestoreStub        func(backupLocation string) error
	restoreMutex       sync.RWMutex
	restoreArgsForCall []struct {
		backupLocation string
	}
	restoreReturns struct {
		result1 error
	}
	restoreReturnsOnCall map[int]struct {
		result1 error
	}
	LiveBucketNameStub        func() string
	liveBucketNameMutex       sync.RWMutex
	liveBucketNameArgsForCall []struct{}
	liveBucketNameReturns     struct {
		result1 string
	}
	liveBucketNameReturnsOnCall map[int]struct {
		result1 string
	}
	BackupBucketNameStub        func() string
	backupBucketNameMutex       sync.RWMutex
	backupBucketNameArgsForCall []struct{}
	backupBucketNameReturns     struct {
		result1 string
	}
	backupBucketNameReturnsOnCall map[int]struct {
		result1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBucketPair) CheckValidity() error {
	fake.checkValidityMutex.Lock()
	ret, specificReturn := fake.checkValidityReturnsOnCall[len(fake.checkValidityArgsForCall)]
	fake.checkValidityArgsForCall = append(fake.checkValidityArgsForCall, struct{}{})
	fake.recordInvocation("CheckValidity", []interface{}{})
	fake.checkValidityMutex.Unlock()
	if fake.CheckValidityStub != nil {
		return fake.CheckValidityStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.checkValidityReturns.result1
}

func (fake *FakeBucketPair) CheckValidityCallCount() int {
	fake.checkValidityMutex.RLock()
	defer fake.checkValidityMutex.RUnlock()
	return len(fake.checkValidityArgsForCall)
}

func (fake *FakeBucketPair) CheckValidityReturns(result1 error) {
	fake.CheckValidityStub = nil
	fake.checkValidityReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketPair) CheckValidityReturnsOnCall(i int, result1 error) {
	fake.CheckValidityStub = nil
	if fake.checkValidityReturnsOnCall == nil {
		fake.checkValidityReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.checkValidityReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketPair) Backup(backupLocation string) (unversioned.BackupBucketAddress, error) {
	fake.backupMutex.Lock()
	ret, specificReturn := fake.backupReturnsOnCall[len(fake.backupArgsForCall)]
	fake.backupArgsForCall = append(fake.backupArgsForCall, struct {
		backupLocation string
	}{backupLocation})
	fake.recordInvocation("Backup", []interface{}{backupLocation})
	fake.backupMutex.Unlock()
	if fake.BackupStub != nil {
		return fake.BackupStub(backupLocation)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.backupReturns.result1, fake.backupReturns.result2
}

func (fake *FakeBucketPair) BackupCallCount() int {
	fake.backupMutex.RLock()
	defer fake.backupMutex.RUnlock()
	return len(fake.backupArgsForCall)
}

func (fake *FakeBucketPair) BackupArgsForCall(i int) string {
	fake.backupMutex.RLock()
	defer fake.backupMutex.RUnlock()
	return fake.backupArgsForCall[i].backupLocation
}

func (fake *FakeBucketPair) BackupReturns(result1 unversioned.BackupBucketAddress, result2 error) {
	fake.BackupStub = nil
	fake.backupReturns = struct {
		result1 unversioned.BackupBucketAddress
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketPair) BackupReturnsOnCall(i int, result1 unversioned.BackupBucketAddress, result2 error) {
	fake.BackupStub = nil
	if fake.backupReturnsOnCall == nil {
		fake.backupReturnsOnCall = make(map[int]struct {
			result1 unversioned.BackupBucketAddress
			result2 error
		})
	}
	fake.backupReturnsOnCall[i] = struct {
		result1 unversioned.BackupBucketAddress
		result2 error
	}{result1, result2}
}

func (fake *FakeBucketPair) Restore(backupLocation string) error {
	fake.restoreMutex.Lock()
	ret, specificReturn := fake.restoreReturnsOnCall[len(fake.restoreArgsForCall)]
	fake.restoreArgsForCall = append(fake.restoreArgsForCall, struct {
		backupLocation string
	}{backupLocation})
	fake.recordInvocation("Restore", []interface{}{backupLocation})
	fake.restoreMutex.Unlock()
	if fake.RestoreStub != nil {
		return fake.RestoreStub(backupLocation)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.restoreReturns.result1
}

func (fake *FakeBucketPair) RestoreCallCount() int {
	fake.restoreMutex.RLock()
	defer fake.restoreMutex.RUnlock()
	return len(fake.restoreArgsForCall)
}

func (fake *FakeBucketPair) RestoreArgsForCall(i int) string {
	fake.restoreMutex.RLock()
	defer fake.restoreMutex.RUnlock()
	return fake.restoreArgsForCall[i].backupLocation
}

func (fake *FakeBucketPair) RestoreReturns(result1 error) {
	fake.RestoreStub = nil
	fake.restoreReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketPair) RestoreReturnsOnCall(i int, result1 error) {
	fake.RestoreStub = nil
	if fake.restoreReturnsOnCall == nil {
		fake.restoreReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.restoreReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBucketPair) LiveBucketName() string {
	fake.liveBucketNameMutex.Lock()
	ret, specificReturn := fake.liveBucketNameReturnsOnCall[len(fake.liveBucketNameArgsForCall)]
	fake.liveBucketNameArgsForCall = append(fake.liveBucketNameArgsForCall, struct{}{})
	fake.recordInvocation("LiveBucketName", []interface{}{})
	fake.liveBucketNameMutex.Unlock()
	if fake.LiveBucketNameStub != nil {
		return fake.LiveBucketNameStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.liveBucketNameReturns.result1
}

func (fake *FakeBucketPair) LiveBucketNameCallCount() int {
	fake.liveBucketNameMutex.RLock()
	defer fake.liveBucketNameMutex.RUnlock()
	return len(fake.liveBucketNameArgsForCall)
}

func (fake *FakeBucketPair) LiveBucketNameReturns(result1 string) {
	fake.LiveBucketNameStub = nil
	fake.liveBucketNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBucketPair) LiveBucketNameReturnsOnCall(i int, result1 string) {
	fake.LiveBucketNameStub = nil
	if fake.liveBucketNameReturnsOnCall == nil {
		fake.liveBucketNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.liveBucketNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeBucketPair) BackupBucketName() string {
	fake.backupBucketNameMutex.Lock()
	ret, specificReturn := fake.backupBucketNameReturnsOnCall[len(fake.backupBucketNameArgsForCall)]
	fake.backupBucketNameArgsForCall = append(fake.backupBucketNameArgsForCall, struct{}{})
	fake.recordInvocation("BackupBucketName", []interface{}{})
	fake.backupBucketNameMutex.Unlock()
	if fake.BackupBucketNameStub != nil {
		return fake.BackupBucketNameStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.backupBucketNameReturns.result1
}

func (fake *FakeBucketPair) BackupBucketNameCallCount() int {
	fake.backupBucketNameMutex.RLock()
	defer fake.backupBucketNameMutex.RUnlock()
	return len(fake.backupBucketNameArgsForCall)
}

func (fake *FakeBucketPair) BackupBucketNameReturns(result1 string) {
	fake.BackupBucketNameStub = nil
	fake.backupBucketNameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeBucketPair) BackupBucketNameReturnsOnCall(i int, result1 string) {
	fake.BackupBucketNameStub = nil
	if fake.backupBucketNameReturnsOnCall == nil {
		fake.backupBucketNameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.backupBucketNameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeBucketPair) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.checkValidityMutex.RLock()
	defer fake.checkValidityMutex.RUnlock()
	fake.backupMutex.RLock()
	defer fake.backupMutex.RUnlock()
	fake.restoreMutex.RLock()
	defer fake.restoreMutex.RUnlock()
	fake.liveBucketNameMutex.RLock()
	defer fake.liveBucketNameMutex.RUnlock()
	fake.backupBucketNameMutex.RLock()
	defer fake.backupBucketNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBucketPair) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ unversioned.BucketPair = new(FakeBucketPair)
