#!/usr/bin/env bash

set -e

export PG_RESTORE_PATH="/var/vcap/packages/database-backuper-postgres/bin/pg_restore"
export MYSQL_RESTORE_PATH="/var/vcap/packages/database-backuper-mysql/bin/mysql"

/var/vcap/packages/database-backuper/bin/database-backup-restore --restore $*
