platform: linux
image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/cryogenics/essentials
    tag: 0.1.84
inputs:
  - name: backup-and-restore-sdk-release
  - name: director-with-iam-profile
    optional: true
run:
  path: backup-and-restore-sdk-release/ci/tasks/sdk-system-blobstore/task.sh
params:
  TEST_SUITE_NAME:
  FOCUS_SPEC:
  BOSH_DEPLOYMENT:
  BOSH_ENVIRONMENT:
  BOSH_CLIENT_SECRET:
  BOSH_CLIENT:
  BOSH_GW_PRIVATE_KEY:
  BOSH_CA_CERT:
  BOSH_GW_USER:
  BOSH_GW_HOST:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_ASSUMED_ROLE_ARN:
  AWS_TEST_BUCKET_NAME:
  AWS_TEST_CLONE_BUCKET_NAME:
  AWS_TEST_UNVERSIONED_BUCKET_NAME:
  AWS_TEST_BUCKET_REGION:
  AWS_TEST_CLONE_BUCKET_REGION:
  AWS_TEST_UNVERSIONED_BUCKET_REGION:
  S3_UNVERSIONED_BUCKET_NAME:
  S3_UNVERSIONED_BUCKET_REGION:
  S3_UNVERSIONED_BACKUP_BUCKET_NAME:
  S3_UNVERSIONED_BACKUP_BUCKET_REGION:
  S3_UNVERSIONED_BPM_BUCKET_NAME:
  S3_UNVERSIONED_BPM_BUCKET_REGION:
  S3_UNVERSIONED_BPM_BACKUP_BUCKET_NAME:
  S3_UNVERSIONED_BPM_BACKUP_BUCKET_REGION:
  S3_UNVERSIONED_LARGE_NUMBER_OF_FILES_BUCKET_NAME:
  S3_UNVERSIONED_LARGE_NUMBER_OF_FILES_BUCKET_REGION:
  S3_UNVERSIONED_LARGE_NUMBER_OF_FILES_BACKUP_BUCKET_NAME:
  S3_UNVERSIONED_LARGE_NUMBER_OF_FILES_BACKUP_BUCKET_REGION:
  AZURE_STORAGE_ACCOUNT:
  AZURE_STORAGE_KEY:
  AZURE_CONTAINER_NAME:
  AZURE_DIFFERENT_STORAGE_ACCOUNT:
  AZURE_DIFFERENT_STORAGE_KEY:
  AZURE_DIFFERENT_CONTAINER_NAME:
  GCP_SERVICE_ACCOUNT_KEY:
  GCP_PROJECT_NAME:
  GCS_BUCKET_NAME:
  GCS_CLONE_BUCKET_NAME:
