---
name: ((deployment-name))

releases:
- name: backup-and-restore-sdk
  version: latest  # replaced by exact version by bosh-deployment-resource in CI

stemcells:
- alias: jammy
  os: ubuntu-jammy
  version: latest  # replaced by exact version by bosh-deployment-resource in CI

instance_groups:
- name: database-backup-restorer
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: jammy
  networks:
  - name: default
  jobs:
  - name: database-backup-restorer
    release: backup-and-restore-sdk
  azs: [z1]

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000
  update_watch_time: 30000
