# Copyright (C) 2017-Present Pivotal Software, Inc. All rights reserved.
#
# This program and the accompanying materials are made available under
# the terms of the under the Apache License, Version 2.0 (the "License”);
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
# http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: ((deployment-name))

releases:
- name: bosh
  version: 271.7.0
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=271.7.0
- name: bpm
  version: latest
  url: https://bosh.io/d/github.com/cloudfoundry/bpm-release

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: latest  # replaced by exact version by bosh-deployment-resource in CI

instance_groups:
- name: postgres
  instances: 1
  vm_type: small
  persistent_disk_type: 10GB
  stemcell: xenial
  networks:
  - name: default
    static_ips: [((db_host))]
  jobs:
  - name: postgres
    release: bosh
    properties:
      postgres:
        user: ((db_username))
        password: ((db_password))
        listen_address: 0.0.0.0
  - name: bpm
    release: bpm
  azs: [((availability_zone))]

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 2000
  update_watch_time: 2000
