on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sdk-template-unit-tests:
    name: SDK Template Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: repo
      - name: Run SDK Template Unit Tests
        run: docker run -v "$PWD/repo:/backup-and-restore-sdk-release" --rm -i "$(docker build -q ./repo/.github/actions/sdk-template-unit-tests/)"
